# Generated by Django 4.1.7 on 2023-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_populate_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro/Prefiro não indicar', 'Outro/Prefiro não indicar')], max_length=100),
        ),
    ]
