# Generated by Django 4.1.7 on 2023-03-30 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_preco_alter_customuser_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('horario', models.DateTimeField()),
                ('duracao', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Duração (min)')),
                ('nota', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_paciente', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_terapeuta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
