# Generated by Django 4.1.7 on 2023-03-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pendingagendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingagendamento',
            name='nota',
        ),
        migrations.AddField(
            model_name='pendingagendamento',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingagendamento',
            name='horario',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
