# Generated by Django 4.1.7 on 2023-03-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_pendingagendamento_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, default='https://tse2.mm.bing.net/th?id=OIP.Jw-MfZVo8aCZLEVTHvMZbQHaE8&pid=Api', null=True, upload_to='profile_pictures/'),
        ),
    ]
