# Generated by Django 4.1.7 on 2023-03-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customuser_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='appointments_per_month_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preco',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Preço'),
        ),
    ]
