# Generated by Django 4.1.7 on 2023-03-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_appointments_per_month_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='appointments_per_month_limit',
            new_name='limite_eventos',
        ),
    ]
