# Generated by Django 4.1.7 on 2023-04-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_appointments_per_month_limit_customuser_limite_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mandar_email',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mandar_whats',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
