# Generated by Django 4.1.7 on 2023-04-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customuser_mandar_email_customuser_mandar_whats'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='num_occurrences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingagendamento',
            name='num_occurrences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
